#!/bin/sh

ln -sf ~/dotfiles/.bashrc ~/.bashrc
ln -sf ~/dotfiles/.ctags ~/.ctags
ln -sf ~/dotfiles/.emacs.d ~/.emacs.d
ln -sf ~/dotfiles/.emacs.d.bk ~/.emacs.d.bk
ln -sf ~/dotfiles/.gvimrc ~/.gvimrc
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/.vim ~/.vim
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.vimrc.appearance ~/.vimrc.appearance
ln -sf ~/dotfiles/.vimrc.basic ~/.vimrc.basic
ln -sf ~/dotfiles/.vimrc.bk ~/.vimrc.bk
ln -sf ~/dotfiles/.vimrc.bundle ~/.vimrc.bundle
ln -sf ~/dotfiles/.vimrc.colors ~/.vimrc.colors
ln -sf ~/dotfiles/.vimrc.completion ~/.vimrc.completion
ln -sf ~/dotfiles/.vimrc.completion.neocomplcache ~/.vimrc.completion.neocomplcache
ln -sf ~/dotfiles/.vimrc.editing ~/.vimrc.editing
ln -sf ~/dotfiles/.vimrc.encoding ~/.vimrc.encoding
ln -sf ~/dotfiles/.vimrc.indent ~/.vimrc.indent
ln -sf ~/dotfiles/.vimrc.macvim ~/.vimrc.macvim
ln -sf ~/dotfiles/.vimrc.moving ~/.vimrc.moving
ln -sf ~/dotfiles/.vimrc.newwindow ~/.vimrc.newwindow
ln -sf ~/dotfiles/.vimrc.plugins_setting ~/.vimrc.plugins_setting
ln -sf ~/dotfiles/.vimrc.search ~/.vimrc.search
ln -sf ~/dotfiles/.vimrc.statusline ~/.vimrc.statusline
ln -sf ~/dotfiles/.vimrc.tags ~/.vimrc.tags
ln -sf ~/dotfiles/.vimrc.vimdiff ~/.vimrc.vimdiff
ln -sf ~/dotfiles/.vimrc.vimtab ~/.vimrc.vimtab
ln -sf ~/dotfiles/.zsh.alias ~/.zsh.alias
ln -sf ~/dotfiles/.zsh.custom ~/.zsh.custom
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.zshrc.bk ~/.zshrc.bk
